### ISSUE TITLE
Threshold for the angle of view so the camera movement won't look sharp

### ISSUE THREAD

**Issue by mesosoi** [Silverware-Games/xanadu-issues#22]
When I was watching this video https://www.youtube.com/watch?v=Yy9_L9-rZeA, I noticed that the camera was moving a lot, even a brief angle change led to a fast, sharp scroll of it. There should be some threshold, until reaching which the camera won't move. Otherwise, the player's eyes will get tired after a few minutes of gameplay.

And here comes another suggestion: the camera should more more smoother, unless it's surplus!

**Comment by michaelplzno** [comment]
There are 2 camera modes: car tracking, and terrain building. Right now the transition between the two is quite awkward and involves a lot of snapping. I will fix this.

In the car movement mode, the camera was designed to work like Mario Kart, but I'd like to make it smoother if that's what you are suggesting?

**Comment by mesosoi** [comment]
> There are 2 camera modes: car tracking, and terrain building. Right now the transition between the two is quite awkward and involves a lot of snapping. I will fix this.

I meant, when the car is driving onto a little bit higher or lower terrain, it is not necessary to move a camera on that small level, the camera should be moved only when there's a big difference between the current camera position and the car position.
I hope that makes sense 😅

> In the car movement mode, the camera was designed to work like Mario Kart, but I'd like to make it smoother if that's what you are suggesting?

Yh, this is the another part of my suggestion.

**Comment by michaelplzno** [comment]
I'll work on it tomorrow!
